using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UniversityProject.Domain.Entities;

namespace UniversityProject.Services.DTOs
{
    public class StudentDto
    {
        ///// <summary>
        ///// Autogenerated id for post entity
        ///// </summary>
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public DateTime EntryDate { get; set; }
        public List<int> SubjectIds { get; set; } 
    }
}
